- name: Install MariaDB Server and Client
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb-server
    - mariadb-client
  become: true

- name: Ensure the MariaDB service is running
  service:
    name: mariadb
    state: started