---
- name: Ensure group "magento_user" exists
  group:
    name: magento_user
    state: present
  become: yes

- name: Create 'magento_user' and add to magento_user and www-data groups
  user:
    name: magento_user
    comment: Magento File System Owner
    group: magento_user
    groups: www-data
  become: yes

- name: Upgrade permissions on magento_user home
  file:
    path: /home/magento_user
    mode: '0770'
  become: yes

- name: Add ubuntu to magento_user group
  user:
    name: ubuntu
    groups: magento_user
  become: yes

- name: Create remote_dir for ansible
  file:
    path: /home/magento_user/.ansible/tmp
    mode: '0770'
    owner: magento_user
    group: magento_user
    state: directory
    recurse: yes
  become: yes

- name: Restart nginx service
  service:
    name: nginx
    state: restarted
  become: yes

- name: Download Composer binary
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer
    mode: '0755'

- name: Install Composer Globally
  command: php composer --install-dir=/usr/bin --filename=composer
  args:
    chdir: /tmp/
  become: yes

- name: Allow read write permissions on /var/www directory
  file:
    path: /var/www
    state: directory
    owner: root
    group: magento_user
    mode: '0775'
    recurse: yes
  become: yes

- name: Clear composer cache
  command: composer clear-cache

- name: Create a new Composer project using the Magento Open Source metapackage
  expect:
    command: composer create-project --repository=https://repo.magento.com/ magento/project-community-edition magento
    responses:
      'Username': '{{ marketplace_user }}'
      'Password': '{{ marketplace_pass }}'
      "Do you want to store credentials for repo.magento.com in /home/magento_user/.composer/auth.json?[Yn]": 'y'
    timeout: 500
  become: yes
  become_user: magento_user
  ignore_errors: yes
  args:
    chdir: /var/www/html

- name: Give g+w permissions to Magento metapackage files
  command: find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +
  become: yes
  args:
    chdir: /var/www/html/magento

- name: Give g+ws permissions to Magento metapackage directories
  command: find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +
  become: yes
  args:
    chdir: /var/www/html/magento

- name: Change ownership of the Magento metapackages to 'magento_user:www_data'
  command: chown -R magento_user:www-data .
  become: yes
  args:
    chdir: /var/www/html/magento
    warn: false

- name: Give u+x permissions to the magento file
  file:
    path: /var/www/html/magento/bin/magento
    state: file
    mode: u+x
  become: yes

- name: Create Magento crontab
  command: php bin/magento cron:install
  become: yes
  become_user: magento_user
  args:
    chdir: /var/www/html/magento
