- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: "yes"
  become: yes

- name: Install package "unzip"
  apt:
    name: "unzip"
  become: yes

- name: Install package "nfs-utils"
  apt:
    name: "nfs-common"
  become: yes

- name: Install package "awscli"
  apt:
    name: "awscli"
  become: yes

- name: Install package "python-botocore"
  apt:
    name: "python-botocore"
  become: yes

- name: Install package "python-boto3"
  apt:
    name: "python-boto3"
  become: yes