- name: Install PHP 7.2 packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - php7.2-common={{ php_version }}
    - php7.2-cli={{ php_version }}
    - php7.2-fpm={{ php_version }}
    - php7.2-opcache={{ php_version }}
    - php7.2-gd={{ php_version }}
    - php7.2-mysql={{ php_version }}
    - php7.2-intl={{ php_version }}
    - php7.2-xsl={{ php_version }}
    - php7.2-mbstring={{ php_version }}
    - php7.2-zip={{ php_version }}
    - php7.2-bcmath={{ php_version }}
    - php7.2-soap={{ php_version }}
    - php7.2-curl={{ php_version }}
  become: yes

- name: Ensure the PHP-FPM service is running
  service:
    name: php7.2-fpm
    state: started
