---
- name: Increase the maximum number of file descriptors
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
  become: yes

- name: Optimize Network Kernel Parameters
  blockinfile:
    dest: /etc/sysctl.conf
    block: |
      net.core.somaxconn = 1024
      net.core.netdev_max_backlog = 5000
      net.core.rmem_max = 16777216
      net.core.wmem_max = 16777216
      net.ipv4.tcp_wmem = 4096 12582912 16777216
      net.ipv4.tcp_rmem = 4096 12582912 16777216
      net.ipv4.tcp_max_syn_backlog = 8096
      net.ipv4.tcp_slow_start_after_idle = 0
      net.ipv4.tcp_tw_reuse = 1
      net.ipv4.ip_local_port_range = 10240 65535
  become: yes

- name: Restart sysctl
  command: sysctl -p
  become: yes

- name: Install GPG key for td-agent
  command: curl https://packages.treasuredata.com/GPG-KEY-td-agent | apt-key add -
  become: yes
  become_user: root
  args:
    warn: false

- name: Install GPG key for td-agent
  command: echo "deb http://packages.treasuredata.com/3/ubuntu/bionic/ bionic contrib" > /etc/apt/sources.list.d/treasure-data.list
  become: yes
  become_user: root
  args:
    warn: false

- name: Update repositories cache
  apt:
    update_cache: yes
  become: yes

- name: Install td-agent
  apt:
    name: td-agent
  become: yes

- name: Start service td-agent, if not started
  service:
    name: td-agent
    state: started
  become: yes
