- name: Download Composer binary
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer
    mode: '0755'

- name: Install Composer Globally
  command: php composer --install-dir=/usr/bin --filename=composer
  args:
    chdir: /tmp/
  become: yes

- name: Allow read write permissions on /var/www directory
  file:
    path: /var/www
    state: directory
    owner: root
    group: magento_user
    mode: '0775'
    recurse: yes
  become: yes

- name: Clear composer cache
  command: composer clear-cache

- name: Create a new Composer project using the Magento Open Source metapackage
  expect:
    command: composer create-project --repository=https://repo.magento.com/ magento/project-community-edition magento
    responses:
      'Username': '{{ marketplace_user }}'
      'Password': '{{ marketplace_pass }}'
      "Do you want to store credentials for repo.magento.com in /home/magento_user/.composer/auth.json?[Yn]": 'y'
    timeout: 500
  become: yes
  become_user: magento_user
  ignore_errors: yes
  args:
    chdir: /var/www/html